### PR TITLE
Rocm Onnxruntime

### PR DESCRIPTION
**Pull request by michaelfeil**
```
cd libs/infinity_emb
make template_docker
```

Install from wheel:
`docker run michaelf34/infinity:0.0.67-rocm-onnx-rc1`

Install from source
`michaelf34/infinity:0.0.67-rocm-onnx-rc3`

Let me know which one works better

### CODE REVIEW

**Comment by michaelfeil** [comment]
@jiahuei

**Comment by jiahuei** [comment]
> @jiahuei 

Hi I believe my colleague has communicated with you on this, thanks for your help 😄🎉

**Comment by michaelfeil** [comment]
@jiahuei Oh, not sure if the above pr was already working, I could not test it myself..

**Comment by tjtanaa** [comment]
@michaelfeil No worries, we will help to test the infinity on the 7900xtx (Radeon) Platform and MI300X (CDNA).

**Pull request merged**
